---
- name: Disable os_prober in grub to avoid update timeouts
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_DISABLE_OS_PROBER="
    line: "GRUB_DISABLE_OS_PROBER=true"
    create: true
    mode: '644'

- name: Update System - Ubuntu
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoremove: true
    update_cache: true

- name: Check if reboot is required after update
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: reboot_if_required

- name: Reboot after update
  ansible.builtin.reboot:
  when: reboot_if_required and reboot_required_file.stat.exists
